<?php
// $Id: pingfm_node.module,v 1.1.2.1 2009/03/27 19:49:11 robloach Exp $

/**
 * @file
 * Provides Custom URL node creation.
 *
 * Also provides a good example of implementing hook_pingfm_custom_url().
 */

/**
 * Implementation of hook_menu().
 */
function pingfm_node_menu() {
  $items['admin/settings/pingfm/node'] = array(
    'title' => 'Node',
    'description' => 'Settings for the Ping.fm Node module.',
    'page arguments' => array('pingfm_node_admin_settings'),
    'page callback' => 'drupal_get_form',
    'file' => 'pingfm_node.module',
    'access arguments' => array('administer pingfm'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Administration settings for the Ping.fm Node module.
 */
function pingfm_node_admin_settings() {
  $form['pingfm_node_type'] = array(
    '#type' => 'radios',
    '#title' => t('Node Type'),
    '#description' => t('The type of node to create when the <a href="!custom_url">custom URL</a> is called. To obtain the correct custom URL to give to Ping.fm, edit your <a href="!user">user account</a>.', array('!custom_url' => 'http://ping.fm/custom/', '!user' => url('user'))),
    '#options' => node_get_types('names'),
    '#required' => TRUE,
    '#default_value' => variable_get('pingfm_node_type', 'story'),
  );
  return system_settings_form($form);
}

/**
 * Implementation of hook_pingfm_custom_url().
 */
function pingfm_node_pingfm_custom_url($user, $data) {
  if ($type = variable_get('pingfm_node_type', NULL)) {
    $node = array(
      'title' => $data['title'],
      'uid' => $user->uid,
      'name' => $user->name,
      'body' => $data['message'],
      'type' => $type,
      'promote' => 1,
    );
    if ($node = node_submit($node)) {
      node_save($node);
    }
  }
}
